### ISSUE TITLE
Add scrollbar for large snippet tooltip

### ISSUE THREAD

**Issue by ecool** [RandomFractals/vscode-snippets-viewer#24]
![image](https://user-images.githubusercontent.com/596184/112674013-ca1c5080-8e3b-11eb-96e4-d21800c86188.png)

Some snippets are very large and the tooltip extends to fill the screen. Maybe set a configurable setting for max tooltip height and add a scrollbar to it whenever it hits that size or is larger than the height of the screen.

Should be possible to do with setting overflow on the tooltip div and setting a max-height through a CSS style.
```css
div {
    overflow-y: auto;
    max-height: 100%;
}
```
May need to do so for width as well with `overflow: auto;` and setting both `max-height` and `max-width`.

**Comment by RandomFractals** [comment]
We might have to log this in vscode repo since that snippet tree view uses TreeItem tooltip provided by vscode api. 

Unless I find CSS class name used for setting that vscode tooltip, I will not be able to fix it with max width, height and overflow on my end.

**Comment by ecool** [comment]
I'm currently looking at a possible way to override/include a custom style into the MarkdownString.

**Comment by ecool** [comment]
Apparently, MarkdownString or however the tooltip is constructed and shown to the user ignores <style> stuff. :(

**Comment by RandomFractals** [comment]
yeah, I don't think we can do that with markdown. It has to be done on the tooltip popup vscode creates for tree items similar to how you get scrollbars on code hints with many method overrides and long docs that we added to intellisense in vscode a release or two ago.

If you don't mind I am going to close this issue since there is nothing we can do to rectify it from extension code.

On the bright side, I have not seen many snippets that long and I am sure as more devs start using markdown string for tree item tooltips this issue will have to be addressed in vscode repo.
