### ISSUE TITLE
Show counters of how many snippets in the category

### ISSUE THREAD

**Issue by usernamehw** [RandomFractals/vscode-snippets-viewer#38]
![Screenshot (460)](https://user-images.githubusercontent.com/9638156/112951652-3fda3200-9144-11eb-9eee-62f1bf6dc7e0.png)

**Comment by RandomFractals** [comment]
good idea. I'll add it.

Thanks for this suggestion.

**Comment by RandomFractals** [comment]
@usernamehw actually, I can do that only for snippeet language and file nodes that are expended since unlike your snippets view extension, I don't load all snippets at once to ensure faster snippets view load and refresh.

**Comment by RandomFractals** [comment]
nope. I tried it and I don't like showing snippet counts in that tree view, even as description.

I just don't find that info very useful. Besides, vscode file explorer doesn't show files count for a directory either. 

I think it's just extraneous information that doesn't provide much value, especially since I can't do it consistently for all snippet language and file parent nodes because I lazy load snippets on those nodes expend.
