### ISSUE TITLE
Workspace defined snippets won't show

### ISSUE THREAD

**Issue by Evileoo** [RandomFractals/vscode-snippets-viewer#94]
Hello

I have a multi-folder workspace and I have like, 10 .code-snippets file in one of them (stored in the .vscode folder)

And no matter what I do they won't show.

Any idea on how to show them ?

**Comment by RandomFractals** [comment]
hey @Evileoo I see you logged this issue and then closed it. Does that mean you figured out how to make it work with multi-folder wokspaces? Quite possible it might not work with that setup. Support of those kind of workspaces came much later after this extension was created and I have not updated it since the initial release with the core features currently listed in docs.

**Comment by Evileoo** [comment]
I found an other one that works :)
